### ISSUE TITLE
In AppVeyor.psm1 there should be an option to change how we detect the files that need code coverage

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#114]
The task to do this in #88 was added because I was going to write the code to do the detection of the files that needed code coverage.  Since this was community provided.  Let's assume it's sufficient.  I'm filing thing just to keep the idea in mind and open it to a discussion.

**Comment by johlju** [comment]
*This does not affect resource modules, like SharePointDsc, that uses the Harness-model. Those resource modules control the code coverage them self by having all testing logic in the harness function in the individual repo. Below is improving functionality for the default shared model.*

Currently it catches all module files (*.psm1) recursively in the folders added here.

https://github.com/PowerShell/DscResource.Tests/blob/7fcd5245841f449951cf98e625f31a711fffe288/AppVeyor.psm1#L279-L282

And as a workaround for resource modules that (wrongly) has helper modules in the root folder this is added as well

https://github.com/PowerShell/DscResource.Tests/blob/7fcd5245841f449951cf98e625f31a711fffe288/AppVeyor.psm1#L260-L262

We should instead add a *Modules* folder to the list above, should be located in the root as well. In the *Modules* folder a resource module helper modules can be located (as .psm1). This should be updated in the [DscResource.Template](https://github.com/PowerShell/DscResources/tree/master/DscResource.Template) as well.

We could add the `$possibleModulePath` as a parameter instead so it's easier to control the module paths if they change in the future, with the following as default values. 

```powershell
$possibleModulePaths = @( 
     'DSCResources', 
     'DSCClassResources',
     'Modules'
 ) 
```

**Comment by johlju** [comment]
@PlagueHO This would help with the code coverage in for example [CertificateDsc](https://github.com/PowerShell/CertificateDsc)? To find if there are parts of the modules that are not covered by tests?

**Comment by johlju** [comment]
Did a test of this with CertificateDsc, and it seems it the helper function are covered. The code coverage percentage dropped, which is positive. 
https://ci.appveyor.com/project/johlju/certificatedsc/build/2.3.6.0#L1486
