### ISSUE TITLE
MD029 - Ordered list item prefix rule should be configured to enforce the style `one'

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#115]
https://github.com/DavidAnson/markdownlint/blob/v0.3.1/doc/Rules.md#md029---ordered-list-item-prefix

The `ordered` style requires manually renumbering lists.

The `one` style is more automatic and the preferred style of the PowerShell/PowerShell project.

**Comment by johlju** [comment]
I thought I'm gonna look into fixing this one as soon as PR #146 has merged. With PR #146 there will be a faster way to override this change per module basis until the specific module can be complaint.
