### ISSUE TITLE
Allow "*Passphrase" or arbitrary parameter name for $mockCredential in Examples

### ISSUE THREAD

**Issue by ryanspletzer** [PowerShell/DscResource.Tests#120]
[Line 458 in Meta.Tests.psm1](https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L458) perhaps should be altered to look for $_ -like "*Passphrase" so that multiple Passphrase credential objects can be mocked out like for example "PfxImportPassphrase" and "FarmPassphrase".

Or, perhaps it could be altered to look for any pscredential object in the command parameters so any name could be used?

Also, it looks like $mockCredential is getting worked out in a PR for #92 so I understand that's still a WIP.

![image](https://cloud.githubusercontent.com/assets/1481108/22869037/079eac32-f16a-11e6-87f5-14f62d7bff6f.png)

**Comment by johlju** [comment]
Thanks for submitting this issue! I add this to the PR #110. This is needed for SharePointDsc as well.

/cc @PlagueHO @TravisEz13
