### ISSUE TITLE
Deploy CodeCov.io code coverage reporting to an active pilot repo

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#122]
We should deploy the support to an active repo that is high quality, or we are trying to get to high quality.

We should get the repo using `appveyor.psm1` first.

@PlagueHO @tysonjhayes @brianfarnhill @johlju, Can you ping me when you have integrated `appveyor.psm1` or if you need help getting that done?

## Example of codecov.io
Here is PR in xWindowUpdate where I increased the code coverage:
https://github.com/PowerShell/xWindowsUpdate/pull/45 

And here is the view of the current code coverage of the main file:
[CodeCov.io - MSFT_xWindowsUpdateAgent.psm1](
https://codecov.io/gh/PowerShell/xWindowsUpdate/src/6a98a224c450acb3d742750795e85325ab6b4489/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.psm1)

**Comment by PlagueHO** [comment]
@TravisEz13 - I'm definitely up for putting this into xNetworking and/or xStorage (both are close to HQRM and working towards it). I was planning on implementing it anyway because it is very awesome.

I'll do this once my PR's go through that bring these resources to use the latest DSCResource.Test changes.

**Comment by tysonjhayes** [comment]
I should be able to work on this once Powershell/xWebAdministration#290 gets merged.

**Comment by TravisEz13** [comment]
@johlju I'll put a PR together for xSQLServer.  It will probably be tomorrow.

**Comment by johlju** [comment]
Awesome! Thanks!

**Comment by PlagueHO** [comment]
@TravisEz13 - I've added the CodeCov.io stuff to my open PR's in xStorage and xNetworking. So hopefully they'll go through soon (although I need [this PR](https://github.com/PowerShell/DscResource.Tests/pull/124) though first).

**Comment by TravisEz13** [comment]
This is done on xSqlServer.  Closing.  Thanks everyone!

**Comment by BrianFarnhill** [comment]
@TravisEz13 I know you closed this one, just letting you know I have it working in a branch of SharePointDsc and will merge it to our dev branch shortly. Awesome work dude

**Comment by TravisEz13** [comment]
@BrianFarnhill thanks, Yeah this was just to deploy one (a pilot)
