### ISSUE TITLE
Integrate PSScriptAnalyzer runs into tests

### ISSUE THREAD

**Issue by KarolKaczmarek** [PowerShell/DscResource.Tests#13]

**Comment by PlagueHO** [comment]
Good idea.

I'm thinking that the code should download the ```PSScriptAnalyzer``` module via the same code as ```Install-ResourceDesigner```.

We could actually convert ```Install-ResourceDesigner``` into a more generic function like: ```Install-SupportModule```. Then ```Install-ResourceDesigner``` and a new ```Install-PSScriptAnalyzer``` could just call the ```Install-SupportModule```.

The actual Pester tests should be straight forward enough then.

I'll take a look at this after I've resolved the problem with PR #11 if you like?

**Comment by KarolKaczmarek** [comment]
Yes, that's exactly how it's done :) 
I've refactored the Install-ResorceDesigner into Install-ModuleFromPowerShellGallery to make it more generic and used it for both ResourceDesigner and PSScriptAnalyzer.

**Comment by PlagueHO** [comment]
Haha! Now that was well done :smile: and quick too - I did a pull on the master branch and saw the code had magically appeared.
