### ISSUE TITLE
Unable to use AppVeyor build worker 'Visual Studio 2017' because of failing when installing Pester 4.x

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#140]
When the build worker does not have WMF 5.1 the common test for module manifest will fail when a module contains class based resources.

https://ci.appveyor.com/project/PowerShell/xsqlserver/build/5.0.1215.0#L202
```
  Describing Common Tests - Module Manifest
    [+] Should contain a PowerShellVersion property of at least 5.0 based on resource types 754ms
    [-] Error occurred in Describe block 54ms
      Exception calling "ParseFile" with "3" argument(s): "Unrecoverable error in Windows PowerShell."
      At C:\projects\xsqlserver\DscResource.Tests\TestHelper.psm1:506 char:9
```

A quick fix for this is to use a build worker that contains WMF 5.1, like the image 'Visual Studio 2017'. But because Pester 3.4.0 is installed default on build worker 'Visual Studio 2017' the test run fails with the following message.

https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.603.0
```
PackageManagement\Install-Package : The version '4.0.3' of the module 'Pester' being installed is not catalog signed. Ensure that the version '4.0.3' of the module 'Pester' has the catalog file 'Pester.cat' and signed with the 
same publisher 'CN=Microsoft Root Certificate Authority 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module '4.0.3' with version '3.4.0' under the directory 'C:\Program 
Files\WindowsPowerShell\Modules\Pester\3.4.0'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```

So I suggest that we add the parameter `-SkipPublisherCheck` to both [rows 58 and 62](https://github.com/PowerShell/DscResource.Tests/blob/dev/AppVeyor.psm1#L58-L62)

**Comment by johlju** [comment]
@PlagueHO, @mbreakey3 and @kwirkykat do you see any issues with this suggestion? Or do you have any other suggestions?

In the meanwhile, as a workaround for this particular case (PR https://github.com/PowerShell/xSQLServer/pull/593) I will try to use the same code to install WMF5.1 as PSDscResources does.

**Comment by PlagueHO** [comment]
This seems OK from my perspective. I've had to do this on a number of my WS2016 servers now as well because of Pester being preinstalled and signed.

**Comment by johlju** [comment]
Oh... This was bad. 😞 Does older PowerShell actually not that parameter on Install-Module? 

https://ci.appveyor.com/project/PowerShell/xfailovercluster/build/1.6.150.0
```
Install-Module : A parameter cannot be found that matches parameter name 'SkipPublisherCheck'.
At C:\projects\xfailovercluster\DscResource.Tests\AppVeyor.psm1:62 char:44
+         Install-Module -Name Pester -Force -SkipPublisherCheck
+                                            ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Module], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Install-Module

```

I will send in a PR to fix this...
