### ISSUE TITLE
Add a Function to Helper Module to automatically upload *_wikicontent.zip to GitHub

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#142]
For the DSC Resources with autodocumenting/wiki content, this content has to be manually uploaded when the module is released. The Wiki content is published as an AppVeyor artifact using the CI process.

However, being manual it is error prone and not a good use of time.

GitHub provides a mechanism where the content can be uploaded by using a Git Clone/Git Push:
https://help.github.com/articles/adding-and-editing-wiki-pages-locally/

What would be useful was a simple cmdlet that could be called either manually or using automation (during the release process the DSC team uses) to:
1. Clone the Wiki Git repo
2. Download the AppVeyor artifact
3. Unzip the artifact to the Wiki Git repo
4. Add a commit message and tag.
5. Push the Wiki Git repo.

This shouldn't be too difficult to achieve.

@kwirkykat , @mbreakey3 , @zjalexander  is this a function that could be automatically called during the release phase for specific modules?

**Comment by kwirkykat** [comment]
@PlagueHO Yeah I can add it to the release script. You have any preference on what repo I try it out on first?

**Comment by PlagueHO** [comment]
@kwirkykat - awesome! I'll get the script created and submit a PR into this repo as a "Helper" function. That way it could be community reviewed etc. I just wanted to check that this would be useful before creating it.

**Comment by BrianFarnhill** [comment]
I'll help test it with SharePointDsc if you like guys - just let me know

**Comment by PlagueHO** [comment]
Awesome, thanks @BrianFarnhill - I'll put it together tomorrow.

**Comment by PlagueHO** [comment]
Haven't got round to this one yet. Will see if I can get to it this week. Sorry!

**Comment by johlju** [comment]
There was one issue left from the issue https://github.com/PowerShell/DscResources/issues/167; "Update Wiki documentation in the build pipeline when PR is merged to master branch.". I think this issue will solve that, so adding it here as a reference.

**Comment by X-Guardian** [comment]
Hi guys, I've written a function that will do this, and am testing it now. I'll raise a PR when I'm happy with it.

**Comment by PlagueHO** [comment]
Cool! Thanks @X-Guardian - looking forward to this. Ideally this will get triggered automatically as part of the build that occurs on the merge to master like what happens with the Example publishing automation.

**Comment by X-Guardian** [comment]
I've plugged it into the `Invoke-AppVeyorDeployTask` with an additional `OptIn` ValidateSet member to trigger it. I've added the actual function into the `WikiPages` module.

I'm just trying to add some additional error processing around the calls to Git, but being an external executable, it is a pain!

**Comment by X-Guardian** [comment]
OK guys, pull request #324 complete. Let me know what you think.
