### ISSUE TITLE
Test for Byte Order Mark (BOM) on module files

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#143]
Module files (.psm1) should be UTF-8, and not UTF-8 with BOM.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-file-encoding

I have at least one resource that has BOM in it's module file, in xSQLServer.

Should we do a check for BOM for this files as well, like we do with markdown files?
Any other file types?

**Comment by PlagueHO** [comment]
This gets my vote.

**Comment by johlju** [comment]
Working on this now.
