### ISSUE TITLE
Issue with file length in validate examples script

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/DscResource.Tests#144]
We are seeing an error in the common tests for the example validation in SharePointDsc - [See example](https://ci.appveyor.com/project/PowerShell/sharepointdsc/build/1.7.0.869#L8322).

I previously touched up this code to get it to ignore the node_modules folder, but I think that isn't cutting it here anymore. I believe it could be the hidden .git directory causing us some grief this time, but I'm still looking in to it.

I wanted to throw this open for discussion as far as how this gets fixed. I see two options

a) I just ignore .git the same way as we ignore node_modules
b) we detect where the psd1 file is for the module and then just copy that folder over. In the case of modules like SharePointDsc that keep the module in a separate directory instead of the root of the repo this would reduce the amount of 'stuff' we need to copy in to be able to validate the modules (and therefore in my opinion adds another reason to want to structure modules this way, but will park that thought there). We should be able to find something like [repo name].psd1 anywhere in the repo and have this work for both styles of directory structure anyway, and this could then solve copying those large additional directories over in the bigger repos. 

Anyone have any thoughts either way on this?

**Comment by johlju** [comment]
I guess the problem we are discussing is on [line 473-481](https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L473-L481).

Option B works for me, but for repositories not using "harness"-model (having the module in a separate folder) we would need to do option A as well, since node_modules folder and .git is in the same folder as the .psd1 file.

**Comment by BrianFarnhill** [comment]
@johlju Yea that's the right bit, I left that out! (This is why I shouldn't raise issues in the morning lol) 

But you're right, I was making an assumption that the non-harness modules would be smaller and therefore less likely to have an issue - but it makes sense to have elements of both here. OK I'll see if I can find some time to code up and test some changes and then go from there.

**Comment by johlju** [comment]
@BrianFarnhill I see you are working on this now, I thought I would help you out with this one. 

The code I got

```powershell
        if ($env:APPVEYOR -eq $true)
        {
            $powershellModulePath = Join-Path -Path (Join-Path -Path $env:SystemRoot `
                                                               -ChildPath 'System32\WindowsPowerShell\v1.0\Modules') `
                                              -ChildPath $repoName

            Write-Verbose -Message ('Copying module from ''{0}'' to ''{1}''' -f $moduleRootFilePath, $powershellModulePath) -Verbose

            # Creates the destination module folder.
            New-Item -Path $powershellModulePath -ItemType Directory -Force

            # Copies all module files into the destination module folder.
            Copy-Item -Path (Join-Path -Path $moduleRootFilePath -ChildPath '*') `
                      -Destination $powershellModulePath `
                      -Exclude @('node_modules','.*') `
                      -Recurse `
                      -Force
        }
```

Tested here (note, removed all unit test and integration test to speed up AppVeyor): 
https://ci.appveyor.com/project/johlju/sharepointdsc/build/1.8.1.11#L1442

**Comment by johlju** [comment]
My working branch is here
https://github.com/johlju/DscResource.Tests/tree/fix-example-common-tests
