### ISSUE TITLE
Validating localization files

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#145]
I think we need a common test that validates the localization strings. With that I mean a test that takes the English localization file and then verifies that against all the keys in the other localization files. This is to find missing keys in either files.

**Comment by johlju** [comment]
I was about to start coding this when I saw @PlagueHO send in PR #162. With that I want to extend this a bit. I would like to add the following checks.

* Does all localization keys exist (in en-US) that are used in the resource?
* Does localization strings (in en-US) contain extra keys?
* Does all other localized languages (se-SV, de-DE, es-ES and so on) have the same keys as the en-US localized strings file.

Hopefully the first two can be done using a Custom PSSA rule (as in PR #162). But the third I see being a normal Pester unit test.

**Comment by johlju** [comment]
If possible we should also add the tests mentioned here https://github.com/PowerShell/DscResources/issues/236#issuecomment-316026293

>Tests:
>
>All localized strings must have an ID.
>No string ID can be equal to any other string ID in the same file.
>The same string ID's should exists on the corresponding key in all localized language files.

**Comment by johlju** [comment]
I made an alpha version of tests - I will add them to DscResource.Tests when I done a little bit more of testing.
 https://github.com/johlju/SqlServerDsc/blob/localization-tests/Tests/Unit/Localization.Tests.ps1

Tests fixed:
- Should have an en-US localization folder.
- The en-US localization folder should have the correct casing.
- Should exist a resource file with the correct name in the localization folder.
- The resource or module should use all the localization string keys from the localization resource file.
- The localization resource file should not be missing any localization string key that are used in the resource or module.
- If there are other localization folders (other than en-US)
  - They should contain a resource file with the correct name.
  - The folders should use the correct casing.
  - All en-US resource file localized string keys must also exist in the resource file.
  - There should be no additional localized string keys in the resource file that does not exist in the en-US resource file.

**Comment by PlagueHO** [comment]
Nice work @johlju - keen to try ot out on some of the ones I maintain. We make it an opt in test?

**Comment by johlju** [comment]
Yes we should make it an opt-in test I think, since it would fail if there were a resource that was not yet using the correct localization style. It is also hard-coded to look for $script:localizedData so it would fail if the variable would be called any other thing. :)
I was thinking I will make the opt-in so that it won’t run anything if not opt-in since it will generate a lot of unnecessary output it it would just skip the tests. 
I made the tests very verbose so new contributors can understand a failing test without digging through the localization files. 
These are the times I would have liked to tell a specific describe/context-block to only output failing tests.
