### ISSUE TITLE
The test Common Tests - Validate Example Files will fail if other Resources are required

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#157]
For example, in xCertificate one of the examples uses xWebAdministration. The example validation fails because the module isn't installed on AppVeyor.

E.g.
https://ci.appveyor.com/project/PlagueHO/xcertificate/build/2.3.74.0#L156

There are several ways this could be resolved that I can see:
1. In the AppVeyor.yml for xCertificate (or any other resource with this problem) import xWebAdministration. I don't think this is a good way to do it because tests will fail on a users computer if they also haven't imported the module.
2. Create a test harness like is done in SharePointDsc and xNetworking (and other repos) that ensures the test environment is configured. Still not ideal IMHO as it requires a test harness -which most repos don't have.
3. The best way might be to use the AST to identify any dependent resource modules and install them from the PSGallery in the code for the `Common Tests - Validate Example Files` tests itself. This would be the more elegant solution IMHO, but it will be a bit more code (I'm looking into this method at the moment).

Obviously this is a bit of an edge case as xCertificate seems to be the only repo with this problem.

**Comment by johlju** [comment]
I would feel that it's better to add any dependent modules in the AppVeyor.yml. Because I think we should not install modules on the users computer, potentially break something. I think, If the user should run the test they should install the modules themself. 

Does this work? Is it possible in the example file add a if-block to evaluate if the module has been installed. If it has it imports the resource using Import-DscResource and add the resources so it can compile the configuration. If the module is not installed a warning message is printed an no Import-DscResource is run and no resource configurations are run. 

Otherwise still add to AppVeyor.yml, but also go for option 3 above, but instead of installing the dependent module it should print an warning message asking the user to install the module and run again.

**Comment by PlagueHO** [comment]
Hi @johlju - I agree - definitely don't want to change a users computer without warning them.

I've created a function that will use the AST to get all the resources imported into a config - it just returns an array of modules. We could then use this list to either warn a user that the tests will fail until the module is installed or if the environment is AppVeyor then we can install the modules automatically.

I could of course just do option 1 - which would be the simplest approach...

Unfortunately, I don't think your suggestion will work - the error actually occurs at the point of dot sourcing the Example config. I tried wrapping the whole thing in an if block and the error still occurs -- this is something to do with the `Import-DscResource` cmdlet being a dynamic command - which seems to behave differently.

**Comment by PlagueHO** [comment]
And just FYI: here is the function I created to retrieve the list of resources in a Config:
```powershell
<#
    .SYNOPSIS
        Gets an array of DSC Resource modules imported in a DSC Configuration
        file.

    .PARAMETER ConfigurationPath
        The path to the configuration file to get the list from.
#>
function Get-ResourceModulesInConfiguration
{
    [CmdletBinding()]
    [OutputType([psobject[]])]
    Param
    (
        [Parameter(Mandatory = $true)]
        [System.String]
        $ConfigurationPath
    )

    # Resource modules
    [psobject[]] $listedModules = @()

    # Get the AST object for the configuration
    $dscConfigurationAST = [System.Management.Automation.Language.Parser]::ParseFile($ConfigurationPath ,[ref]$null,[ref]$Null)

    # Get all the Import-DscResource module commands
    $importDscResourceCmds = $dscConfigurationAST.EndBlock.FindAll( {
        $args[0] -is [System.Management.Automation.Language.DynamicKeywordStatementAst] -and `
        $args[0].CommandElements[0].Value -eq 'Import-DscResource'
    },$true )

    foreach ($importDscResourceCmd in $importDscResourceCmds)
    {
        $parameterName = 'ModuleName'
        $moduleName = ''
        $moduleVersion = ''

        foreach ($element in $importDscResourceCmd.CommandElements)
        {
            # For each element in the Import-DscResource command determine what it means
            if ($element -is [System.Management.Automation.Language.CommandParameterAst])
            {
                $parameterName = $element.ParameterName
            }
            elseif ($element -is [System.Management.Automation.Language.StringConstantExpressionAst] -and `
                $element.Value -ne 'Import-DscResource')
            {
                switch ($parameterName)
                {
                    'ModuleName'
                    {
                        $moduleName = $element.Value
                        break
                    } # ModuleName
                    'ModuleVersion'
                    {
                        $moduleVersion = $element.Value
                        break
                    } # RequiredVersion
                } # switch
            }
            elseif  ($element -is [System.Management.Automation.Language.ArrayLiteralAst])
            {
                <#
                    This is an array of strings (usually something like xNetworking,xWebAdministration)
                    So we need to add each module to the list
                #>
                foreach ($item in $element.Elements)
                {
                    $listedModules += [psobject] @{
                        ModuleName    = $item.Value
                        moduleVersion = ''
                    }
                } # foreach
            } # if
        } # foreach

        # Did a module get identified when stepping through the elements?
        if (-not [String]::IsNullOrEmpty($moduleName))
        {
            $listedModules += [psobject] @{
                ModuleName    = $moduleName
                moduleVersion = $moduleVersion
            }
        } # if
    } # foreach

    return $listedModules
}
```

**Comment by PlagueHO** [comment]
So what I've done is modified the 'Common Tests - Validate Example Files' test so that it will identify any resource modules that are required but missing from the machine. If the machine is an AppVeyor one it will just install them and continue the tests - but if the machine is a user machine it will warn the user but continue the test (which will fail):
![image](https://user-images.githubusercontent.com/7589164/28152624-9c5d22d4-67f5-11e7-9572-673d13a11c9d.png)

Enabling this actually helpfully identified broken examples in xCertificate :grin:

Does this sound like it would would be acceptable for the community?

**Comment by johlju** [comment]
@PlagueHO I'm totally okay with your solution. Awesome work! 😃 

I think this will help us when we need to add xFailOverCluster resource in the examples for xSQLServer!
