### ISSUE TITLE
Test for Byte Order Mark (BOM) on script files (.ps1)

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#160]
Script files (.ps1) should be UTF-8, and not UTF-8 with BOM.
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#correct-file-encoding

I saw that there is tests script files that has BOM on them in xSQLServer.

I suggest we add another check for BOM on script files (.ps1). And make that Opt-In as well.

Opt-In using:
```json
[
    "Common Tests - Validate Script Files"
]
```

**Comment by PlagueHO** [comment]
Sounds good to me.
