### ISSUE TITLE
Run common tests on DscResource.Tests repository

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#170]
I think we need to add so that we run common tests on this repository. This would prevent issue like #169.

**Comment by PlagueHO** [comment]
Yep - agreed. I think we'd also want to implement a really basic AppVeyor.yml file to run the validation checks.

**Comment by johlju** [comment]
I working on this. See if I can fix this. :)

**Comment by johlju** [comment]
I have found a solution to use DscResource.Tests to test it self. But I have to get some changes in for this to work. So I will send in two PR's. 

* The first PR will change the code so it is possible for the second PR to pass the tests . Just minor fixes.
* The second PR will actually be the one that enables the testing, by adding an AppVeyor.yml.

**Comment by johlju** [comment]
@kwirkykat is it possible to turn on AppVeyor for this repo so that PR #175 can work?

**Comment by johlju** [comment]
@mbreakey3 is it possible to turn on AppVeyor for this repo so that PR #175 can work?
