### ISSUE TITLE
Need a common tests to test the length of the relative file paths

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#188]
A relative file path cannot exceed 120 characters to be able to compile a configuration in Azure Automation.

See more in issue https://github.com/PowerShell/DscResources/issues/310.

**Comment by johlju** [comment]
Heard from @kwirkykat that Azure Automation Team is working on the long path issue. Let's await that before making any tests or changing the xSQLServer module. There probably is gonna be a hard limit, but hopefully it will be much higher.

**Comment by johlju** [comment]
See update in this comment https://github.com/PowerShell/xSQLServer/issues/851#issuecomment-341820454. 

So maybe we should make a test that checks for 129 characters in the (relative) full path. This could then easily be expanded if the file length can exceed that later.

**Comment by PlagueHO** [comment]
So the Azure Automation team are still working on the long path issue?

But it does sound like this would be a worthwhile improvement. Do we know if any other resource modules have hit this?

**Comment by johlju** [comment]
Yes, @mgreenegit is on top of the issue. But guess the issue was more difficult to resolve than anticipated since @mgreenegit is working on fixing the path lengths in xSQLServer. 

I have not heard any other having this issue. In xSQLServer there are long example file names etc which does not help this issue, due to the current descriptive resource names which makes them longer. I think any resource module with a file path exceeding this limit that is published with the release could potentially lead to this issues.

**Comment by johlju** [comment]
I have created a temporary common test in the PR https://github.com/PowerShell/SqlServerDsc/pull/937 which can be used as a template for creating the real common test.
