### ISSUE TITLE
Failing tests in TestHelper.Test.ps1

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/DscResource.Tests#194]
AppVeyor tests are failing in SharePointDsc with the following error:

  Describing TestHelper Unit Tests
    [-] Error occurred in Describe block 56ms

      RuntimeException: Multiple Script modules named 'TestHelper' are currently loaded.  Make sure to remove any extra copies of the module from your session before testing.

      at Get-ScriptModule, C:\Program Files\WindowsPowerShell\Modules\Pester\4.0.6\Functions\InModuleScope.ps1: line 115

**Comment by ykuijs** [comment]
@BrianFarnhill

**Comment by johlju** [comment]
@ykuijs Please see this PR to fix this for testing the "Harness"-model https://github.com/PowerShell/xStorage/pull/119.

Issue: https://github.com/PowerShell/DscResource.Tests/issues/189

**Comment by ykuijs** [comment]
Implemented change, new AppVeyor tests now running

**Comment by ykuijs** [comment]
@johlju Tests have succeeded, will implement this fix in our Dev branch as well. Thanks for the help!

Closing this issue

**Comment by johlju** [comment]
@ykuijs Happy to help 😄
