### ISSUE TITLE
Assert-VerifiableMocks was renamed to Assert-VerifiableMock in Pester 4.0.7

### ISSUE THREAD

**Issue by regedit32** [PowerShell/DscResource.Tests#196]
TestRunner.Tests.ps1 has a call that uses Assert-VerifiableMocks.  A breaking change in Pester 4.0.7 renamed `Assert-VerifiableMocks `was renamed to `Assert-VerifiableMock`.  [https://github.com/pester/Pester/releases/tag/4.0.7](url)

**Comment by PlagueHO** [comment]
@kwirkykat - do you want me to submit a PR to get this one fixed? Happy to do it, just didn't want to submit it if you're already onto it.

**Comment by kwirkykat** [comment]
@PlagueHO I'm not working on it already. I can review the PR if you'd like to submit it 🙂

**Comment by PlagueHO** [comment]
@kwirkykat - Awesome! Just submitted the PR :grin: Will tag you!

**Comment by johlju** [comment]
Great team work fixing this! 😄
