### ISSUE TITLE
Migrate Pester Test Syntax from v3 -> v4

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#199]
**Details of the scenario you tried and the problem that is occurring:**
As of Pester v4 the syntax of the `Should` cmdlet has changed from `Should Be` to `Should -Be`.

There is a helpful script that can be used to easily perform the conversion:
https://gist.github.com/indented-automation/aeb14825e39dd8849beee44f681fbab3

This script should be used to correct the Pester syntax.

**Comment by PlagueHO** [comment]
@kwirkykat - do you have any objections to us doing this? If you're happy with us doing this them I'm happy to submit the PR for it.

**Comment by kwirkykat** [comment]
@PlagueHO No objections. Updating is great! Pester also broke some of the modules recently by renaming `Assert-VerifiableMocks` to Assert-VerifiableMock` which will also need to be updated for any future Pester versions

**Comment by PlagueHO** [comment]
Awesome! I'll get it done once https://github.com/PowerShell/DscResource.Tests/pull/200 is through.
