### ISSUE TITLE
Update WikiPages script to include EmbeddedInstance

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/DscResource.Tests#201]
The script that generates the Wiki content retrieves the datatype from the schema and uses that in the Wiki page. When a parameter is a credential, the datatype is String but it also has an EmbeddedInstance that specifies it has to be of type MSFT_Credential.

Can we update the Wikipages script to include the EmbeddedInstance in the datatype column?

For example:
| **DatabaseServer** | Required | String | Server that will host the databases ||
| **Account** | Required | String (MSFT_Credential) | The account to use ||

**Comment by johlju** [comment]
Wouldn’t be better to change it, in the wiki page, to the type `PSCredential` when the “EmbeddedInstance” is found?  Removing `String` altogether?
It feels to me that it would be more natural.

**Comment by ykuijs** [comment]
That sounds even better! Will update my PR.

**Comment by ykuijs** [comment]
Done, PR ready for review

**Comment by ykuijs** [comment]
Merged in PR #202
