### ISSUE TITLE
CodeCov Upload Error Message

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#203]
An [error](https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.786.0#L4671) has recently started appearing during upload of the code coverage results to CodeCov.io. _This error appears to not actually prevent upload or fail the build, so is not critical._

The error occurs when calling the `codecov` Python script from [this line](https://github.com/PowerShell/DscResource.Tests/blob/dev/DscResource.CodeCoverage/CodeCovIo.psm1#L335) of the `CodeCovIo` module.

The output of the `codecov` python can be seen in the `CodeCovUpload.log` artifact stored in the [AppVeyor build artifacts](https://ci.appveyor.com/project/PowerShell/xnetworking/build/3.1.786.0/artifacts). This shows no errors:

```text

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.10

[90m==>[0m Detecting CI provider
    AppVeyor Detected
[90m==>[0m Preparing upload
    Error running `cd 'C:\projects\xnetworking' && git ls-files`: None
[31mXX>[0m Skip processing gcov
[90m==>[0m Collecting reports
[31mXX>[0m Searching for reports disabled
    Targeting specific files
    [32m+[0m C:\Users\appveyor\AppData\Local\Temp\1\codeCov.json bytes=1015201
[90m==>[0m Uploading
    .url https://codecov.io
    .query service=appveyor&commit=287671eeb0117d7374e8102aaf6c329c9d9a7607&package=py2.0.10&branch=dev&build=bsjueksk050yjjm6&job=PowerShell%2Fxnetworking%2F3.1.786.0&pr=291&slug=PowerShell%2FxNetworking
    Pinging Codecov...
    Uploading to S3...
[92m    https://codecov.io/github/PowerShell/xNetworking/commit/287671eeb0117d7374e8102aaf6c329c9d9a7607[0m
```

It also shows the artifact being uploaded. The result can also be seen in CodeCov.io.

The error seems to occur or be outputted into the error stream somewhere in this Python code:
https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py

The last changes to this code was made 5 days ago. looking back through AppVeyor logs, this error started appearing at least 4 days ago but not more than 6 days ago - so this would track with the recent changes made to the CodeCov Python.

This is occurring in all repos that process and upload code coverage.

**Comment by johlju** [comment]
Submitted an issue https://github.com/codecov/codecov-bash/issues/108.

**Comment by johlju** [comment]
Submitted an issue https://github.com/codecov/codecov-python/issues/129.

*Submitted to the wrong repo at first, deleted that comment.*

**Comment by PlagueHO** [comment]
Great job @johlju - sorry I haven't had time to look into this (have had to do actual "work work" over the break - lots of work on creating security layers around CosmosDb and API Management). This month might be a bit slow on the DSC side from me unfortunately due to too many other commitments :cry:

**Comment by johlju** [comment]
@PlagueHO No worries. Sorry to hear you had a lot of work over the holidays :/ This month will be a bit slower for me as well, after this week at least. Still on vacation, back at work on the 8th and have a deadline at end of January.

**Comment by ramlongcat** [comment]
i have the same issue and my repo is correct.
im using AppVeyor and a build that used to work in December is now failing with that exact error message.
FYI in my experience the error started to appear around December 15th.

**Comment by ramlongcat** [comment]
the only meaningful change i see around those dates is [that one](https://github.com/codecov/codecov-python/commit/bc70732bc1e7fef2167afaa25f84a5d25af947f3#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23).
i'm not sure -- but i think the issue could be the content type on [line 730](https://github.com/codecov/codecov-python/commit/bc70732bc1e7fef2167afaa25f84a5d25af947f3#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23R730) hasn't been updated.
i'd try to change `'Content-Type': 'text/plain'` to `'Content-Type': 'text/plain; charset=utf-8'` since
the default for this content type is `us-ascii` according to [the W3C spec](https://www.w3.org/Protocols/rfc1341/7_1_Text.html).

**Comment by ramlongcat** [comment]
interesting ! now that you're saying this i compared my old/working codecov output:
```
==> Detecting CI provider
    AppVeyor Detected
==> Preparing upload
XX> Skip processing gcov
==> Collecting reports
```
with the current one:
```
==> Detecting CI provider
    AppVeyor Detected
==> Preparing upload
    Error running `cd 'C:\projects\parkserver' && git ls-files`: None
XX> Skip processing gcov
==> Collecting reports
```
it seems you're right.

**Comment by ramlongcat** [comment]
but [that change](https://github.com/codecov/codecov-python/commit/63546cf704e786b4e30ec66972b822eff8d4f69a) occurred more than 2 years ago ?

**Comment by ramlongcat** [comment]
that same line is using `root` and it has been changed [here ](https://github.com/codecov/codecov-python/commit/d8f9c7bcbf3217be472bd9295934dab4ff31bb7c#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23) using `quote(root)` around those dates.

**Comment by johlju** [comment]
It was just a possible issue. Our thought was that something changed in Window (how Python is calling this `&&`), because the error in the issue description says`Error running `cd 'C:\projects\xnetworking' && git ls-files`: None`. 

But the 'root' row you found could be it too.

**Comment by PlagueHO** [comment]
That is all some interesting info. I did confirm that this issue also occurs when executing locally (I had to trick the machine into pretending to be AppVeyor by defining some environment variables that the CodeCov.io looks for). But as this issue seems to be mostly harmless I didn't get much further. But it would be great to resolve. I think @johlju's suggestion that this could be caused by running from PowerShell instead of CMD could be a big possibility.

But what might have changed was the version of Python and the behavior of the "try_to_run()" function. I'm thinking that this error may have always occurred, it is just the error never got pushed into the error stream so we never saw it. But I am just guessing - because I can't see any other change that could have caused this.

**Comment by ramlongcat** [comment]
FYI i manually patched [the line i was talking about](https://github.com/codecov/codecov-python/commit/d8f9c7bcbf3217be472bd9295934dab4ff31bb7c#diff-ed4cb86e1f4a5c5feeecc37b90ec6a23R557) to be a comment and my uploads now work.

**Comment by johlju** [comment]
@PlagueHO What do think about switching to this [.exe report uploader for Codecov](https://github.com/codecov/codecov-exe). It seems that the [prerequisites](https://www.appveyor.com/docs/build-environment/#tools) 'choco' is installed on the build worker.

```
choco install codecov
.\codecov.exe -f <path to coverage report> -t <Codecov upload token>
```

I just saw it, so I haven't done anything more than read the README.md.

**Comment by johlju** [comment]
The problem seems to escalate, now more errors are shown. The errors still does not affect functionality (yet). 

https://ci.appveyor.com/project/PowerShell/xpowershellexecutionpolicy/build/1.0.66.0#L279

**Comment by PlagueHO** [comment]
Good idea, but it looks like the CodeCov.exe uses the same Python code to upload the report. So we're seeing the same issue. Such a pain!

**Comment by johlju** [comment]
Oh, I hoped it did not do that :/

**Comment by johlju** [comment]
We have the [Ruby}(https://github.com/codecov/codecov-ruby) one, and the [Pearl](https://github.com/codecov/codecov-perl) one as well. Not can those use the Pyhton script? 🤔

**Comment by PlagueHO** [comment]
The Ruby one looks like it might work - Choco can be used to install Ruby pretty easily. Great ideas!

**Comment by PlagueHO** [comment]
Oh wait - I missed the message from @ramlongcat - great idea there. Might be worth looking into more. Thanks @ramlongcat and sorry I didn't see your post. What do you think @johlju

**Comment by johlju** [comment]
I’m all for the idea, if it solves the problem. :) Fixing the problem in the script at source I think would be the best option. Parsing the script at our end could maybe be problematic if changes occurs at source?

**Comment by johlju** [comment]
Looks like `codecov.exe` actually solves this. Sent in a PR #223
