### ISSUE TITLE
Code coverage does not analyze code in all module files in this repository

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#208]
Currently when this repository is tested, the code coverage is only reported for the module files in the root folder.
Thats because the following code block does not add more than the modules in the root folder. 

https://github.com/PowerShell/DscResource.Tests/blob/f9e3dfd3eb9d7b6a9225e2cfba68b79ffe1cab36/AppVeyor.psm1#L250-L268

Suggest we use the helper function `Test-IsRepositoryDscResourceTests` to see if we are testing this repository, and if so, add all the module files (.psm1) under sub folders as well. So we can get code coverage for all the helper modules like DscResource.AnalyzerRules, DscResource.CodeCoverage and DscResource.DocumentationHelper.

**Comment by PlagueHO** [comment]
Good call @johlju - this looks like a goo idea.

So there would be three different code coverage file patterns:
1. Test Harness DSC repo
2. Normal DSC repo
3. DSCResources.Tests repo

So the `else` in your code block above could be replaced by an `elseif (Test-IsRepositoryDscResourceTests)`?

**Comment by johlju** [comment]
Yes my thought was three patterns. I think we need to add and `elseif` before the else in the block above, so that a new resource module that does not have a DSCResource module does get coverage (a extreme edge case). 

I think new `elseif`-block should have the path `$env:APPVEYOR_BUILD_FOLDER\**\*.psm1` as well as the path in else block (don’t think the former fetches modules in root?). So we could add an `if`-block inside the `else`-block, if that is less code rows.

**Comment by johlju** [comment]
Actually there will be these three file patterns since the code block that will change does not affect Harness-repos.

1. Normal resource module repo with DSCResource-folder (repo with resources)
1. Normal resource module repo without DSCResource-folder (repo without resources)
1. DscResources.Tests repo

The second and the third might be able to be the same.
