### ISSUE TITLE
Improve Wiki Generation - Store Wiki Root page in Main Repo

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#227]
Currently the Wiki Root page is updated manually with new resources. This should be changed so that the it can be stored in the main repo as a WIKIROOT.MD and have the resource list merged in with it.

**Comment by X-Guardian** [comment]
I've written code for this that plugs in to the new `Publish-WikiContent` function.
It copies any files in a `/WikiSource` directory of the repo into the Wiki.

You can see an example in my fork of the [xActiveDirectory](https://github.com/X-Guardian/xActiveDirectory/wiki) module.

I could add this to PR #324, or wait till that's merged and raise a new PR. What do you guys think?

**Comment by johlju** [comment]
I suggest we add that when the first is merged, so we don’t make the PR unnecessarily big.
