### ISSUE TITLE
Improve Wiki Generation - Automatically Generate _SIDEBAR.MD

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#228]
The _SIDEBAR.MD is currently manually updated/generated. It should be generated automatically.

**Comment by X-Guardian** [comment]
I've written code for this that plugs in to the new `Publish-WikiContent` function.
It loops through the list of files in the Wiki and adds a list entry to the sidebar for each one consisting of a link built from the text of the first line of the file (trimmed of any header markdown) linked to the base file name.
You can see an example in my fork of the [xActiveDirectory](https://github.com/X-Guardian/xActiveDirectory/wiki) module.
It definitely looks better than the standard pages list.

I could add this to PR #324, or wait till that's merged and raise a new PR. What do you guys think?

**Comment by johlju** [comment]
I suggest we add that when the first is merged, so we don’t make the PR unnecessarily big.
