### ISSUE TITLE
Codecov is no longer generate for "Harness"-model resource modules

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#229]
The problem is that the parameter `CodeCoverage` is not used by the Harness-module repositories so line 913 will never be `$true`.

https://github.com/PowerShell/DscResource.Tests/blob/f1f2623aeec122c02635447b1d4e9413e2d7d923/AppVeyor.psm1#L911-L916

**Comment by PlagueHO** [comment]
@johlju: I wonder: if we want to bring the auto-documentation modules more inline with the other modules, perhaps it would be better to add the `CodeCoverage` parameter to the auto-documentation repos?
