### ISSUE TITLE
test template scripts only run without error in root of module.

### ISSUE THREAD

**Issue by jcwalker** [PowerShell/DscResource.Tests#24]
When using the template for the integration test.  The first thing the script template does is download a DscResource.Test directory which contains TestHelper.psm1 from GitHub.  The template script calls TestHelper.psm1 which throws error because it can’t locate the module manifest file which is located in the root folder of the module.  TestHelp.psm1 is looking for this file in the Tests\Integration folder.  TestHelper.psm1 is using $MyInvocation.MyCommand.Path to get the path to the module manifest. $MyInvocation.MyCommand.Path is going to resolve to whatever folder TestHelper.psm1 is located it.   This goes against the testing guidance to create a Tests\Integration folder as the test will only run without error if they ran from the root of the module.

**Comment by PlagueHO** [comment]
Hi @jcwalker:

1. which folder is set as the current folder when you call ```Invoke-Pester```?
2. Are you in the Tests\Integration or the DSC Module Root folder when you call ```Invoke-Pester```? If the current folder is anything but the DSC Module Root folder the tests will fail.

Regarding the testing guidance, are you referring to [this](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) document? It might be that the testing guidance needs tweaking.

Thanks!

**Comment by jcwalker** [comment]
Hey @PlagueHO 
Yes I am in the Tests\Integration folder.  And yes I'm referring to that document.
So I should be calling Invoke-Pester from the module root folder and not from the Test\Integration folder?

Thanks for being so quick to respond to this.

**Comment by KarolKaczmarek** [comment]
Currently Initialize-TestEnvironment is written in a way that it requires to call Invoke-Pester from root folder, however I think we should modify it so that it works regardless of the location where we invoke tests from (this way we can easily execute either unit or integration tests only).

**Comment by PlagueHO** [comment]
@KarolKaczmarek - that is a good idea - didn't think of that (I've usually just specified the ```-script``` parameter on ```invoke-pester```). Although if you do run Invoke-Pester from a subfolder you'd end up with a copy of the DSCResource.Test in that folder as well - but I don't see that as a problem.

We could look for ```"$DSCModuleName.psd1"``` in the current folder and if it is not found, walk up the directory tree to find it (that is risky though). Better idea might be to check current folder and if the two leaf nodes are named "Tests\Integration" then adjust the ```$RelativeModulePath``` accordingly (e.g. ```$RelativeModulePath = "..\..\$DSCModuleName.psd1"```

Would do something similar with the unit test path as well.

Should I give either of these two approaches a try and submit a PR if appropriate? Or is there a better way?

Tx

**Comment by PlagueHO** [comment]
@jcwalker, glad to help. At the moment, the test initialization code does need to be called from the root folder of your DSC Module (via ```INvoke-Pester```), but as @KarolKaczmarek suggests, this might be able to be changed as executing just Integration or Unit tests only would be useful.

**Comment by KarolKaczmarek** [comment]
@PlagueHO 
DscResource.Tests should always be cloned to the root directory, so that regardless of where we call tests from, there's always only one copy of it present.

To achieve that, just make sure that you obtain the root path from the integration_template.ps1, you can do it in the same way as it's done in Initialize-TestEnvironment:
```PowerShell
[String] $moduleRoot = Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path)
```

I believe this should also fix the problem @jcwalker reported.

**Comment by PlagueHO** [comment]
@KarolKaczmarek, your suggestion works 100% :+1: and does indeed resolve @jcwalker's issue.

I'll submit a PR for the test.templates in DSCResources.

**Comment by KarolKaczmarek** [comment]
Awesome, thanks!

**Comment by jcwalker** [comment]
Thanks @KarolKaczmarek  and @PlagueHO .  That was a fast resolution!

**Comment by PlagueHO** [comment]
Glad to help and good catch :smile:

**Comment by KarolKaczmarek** [comment]
Fixed in https://github.com/PowerShell/DscResources/pull/85
