### ISSUE TITLE
Add Custom PSSA Checks for Keyword Style Rules

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#244]
This issue is to add some PSSA checks for keyword style rule violations. It is part of implementing https://github.com/PowerShell/DscResources/issues/404.

The following keywords/statements need to be tested (tick them off as they are implemented):
- [ ] : begin
- [ ] : break
- [ ] : catch
- [ ] : class
- [ ] : continue
- [ ] : data
- [ ] : define
- [ ] : do
- [ ] : dynamicparam
- [ ] : else
- [ ] : elseif
- [ ] : end
- [ ] : enum
- [ ] : exit
- [ ] : filter
- [ ] : finally
- [ ] : for
- [ ] : foreach
- [ ] : from
- [ ] : function
- [ ] : hidden
- [ ] : if
- [ ] : in
- [ ] : inlinescript
- [ ] : param
- [ ] : process
- [ ] : return
- [ ] : static
- [ ] : switch
- [ ] : throw
- [ ] : trap
- [ ] : try
- [ ] : until
- [ ] : using
- [ ] : var
- [ ] : while
- [ ] : while (clause in do...while)

**Comment by PlagueHO** [comment]
Any objections if we implement this one @johlju , @gaelcolas ? It'll save a lot of PR comments.

**Comment by SSvilen** [comment]
I think this was resolved with my PR (#346 )? 
@PlagueHO  @johlju

**Comment by PlagueHO** [comment]
@SSvilen - yes, I think you're right. I'll close.
