### ISSUE TITLE
Bug in Wiki Generation when Used without Harness

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#245]
There is a bug in the Wiki generation code in `Invoke-AppveyorAfterTestTask`. One of the variables was incorrect and the value was being picked up from the AppVeyor.yml file definition instead of being passed in as a parameter.

See: https://ci.appveyor.com/project/PlagueHO/wsmandsc#L989

**Comment by PlagueHO** [comment]
This bug will affect any Wiki generation module where the variable `$mainModuleFolder` is defined in AppVeyor.yml (@ykuijs). If you remove the variable `$mainModuleFolder` from AppVeyor.yml then this bug is exposed. So fixing this bug will allow the `$mainModuleFolder` to be removed from AppVeyor.yml.

**Comment by johlju** [comment]
Resolved by PR #246
