### ISSUE TITLE
Example publishing will publish exampes with number prefix

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#254]
Currently if the filename of an example contain a number prefix '1-', '2-', etc. it will correctly remove that when validating that the filename and configuration name is the same. 
But, when publishing the example, the number prefix is _not_ removed which will make the example fail to import in Azure Automation.

Before publishing the example need to be saved to a temporary file without thew prefix, and published using that temporary file.

https://github.com/PowerShell/DscResource.Tests/blob/8d30ff1fc8cf91cd78f915cfc3e5eab2cdfea737/DscResource.GalleryDeploy/DscResource.GalleryDeploy.psm1#L208

**Comment by PlagueHO** [comment]
Hi @johlju - are you working on this one? I'm happy to submit a PR for it if not as I was thinking of adding the numbers back into the CertificateDsc PR https://github.com/PowerShell/CertificateDsc/pull/143

**Comment by johlju** [comment]
If you have time to fix this then please do :)

**Comment by PlagueHO** [comment]
@johlju - In progress!

**Comment by PlagueHO** [comment]
@johlju - paused work on this as I've found an issue with the Wikicontent generation when the .PSScriptInfo is in the example. I'll raise an issue and fix it before I fix this one.

**Comment by johlju** [comment]
@PlagueHO I take this one! I will send in a PR shortly.
