### ISSUE TITLE
New-DscSelfSignedCertificate: Update informational messages

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#259]
In Appveyor.psm1 there is a line that write the information below. Maybe we should copy that line into the `New-DscSelfSignedCertificate` function instead, that actually creates the certificate.
```
Write-Info -Message ('Created self-signed certificate ''{0}'' ...
```

And in the Appveyor.psm1 changed the line to

```
Write-Info -Message ('Using self-signed certificate ''{0}'' ...
```

The it won't look like the certificate is created twice, when it actually is only created the first time `New-DscSelfSignedCertificate` is called.
https://ci.appveyor.com/project/PlagueHO/activedirectorycsdsc/build/1.1.49.0#L17

**Comment by PlagueHO** [comment]
I'll get this done! Leave it with me.
