### ISSUE TITLE
Move change log from README.md to CHANGELOG.md

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#284]
I suggest we move the change log from within the README.md to a separate file CHANGELOG.md. The change log is so long now so I think it suits better in its own file.

**Comment by PlagueHO** [comment]
Love it. I've been meaning to suggest this for months. Great idea.

**Comment by johlju** [comment]
Tagged this issue my mistake form a PR, this issue is not being worked on by me in any PR. Still up for grabs by anyone. 🙂

**Comment by johlju** [comment]
When this issue is resolved, the PULL\_REQUEST\_TEMPLATE.md should be updated to reflect the move.
