### ISSUE TITLE
AppVeyor: PowerShellGet fails when PackageManagement update gives error

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#292]
Test framework installs PowerShellGet.

https://github.com/PowerShell/DscResource.Tests/blob/a522ade40d959fc931dfc9eb2a4ec096b7e3afb1/AppVeyor.psm1#L42-L49

Currently the PowerShellGet fails because the PackageManagement module is in use. 

```
The version '1.1.7.2' of module 'PackageManagement' is currently in use. Retry the operation after closing the applications.
```

This is not a problem at the moment since the AppVeyor build worker recently was updated with the latest PackageManagement and the latest PowerShellGet. Thus, this problem started happen.

```
    Directory: C:\Program Files\WindowsPowerShell\Modules

ModuleType Version    Name                                ExportedCommands                                                                                                                                                           
---------- -------    ----                                ----------------                                                                                                                                                           
Script     1.1.7.2    PackageManagement                   {Find-Package, Get-Package, Get-PackageProvider, Get-PackageSource...}                                                                                                     
Script     2.0.0      PowerShellGet                       {Find-Command, Find-DSCResource, Find-Module, Find-RoleCapability...} 
```

Open this issue to track this, if this is still a problem when next version of PowerShellGet is released.

**Comment by PlagueHO** [comment]
I think this one is no longer an issue:
https://ci.appveyor.com/project/PowerShell/NetworkingDsc/branch/dev?fullLog=true#L19

So, I reckon we close this one unless it pops up again.

**Comment by johlju** [comment]
Let's close this issue.

**Comment by PlagueHO** [comment]
Cool. Thanks @johlju
