### ISSUE TITLE
Run Test-xDscResource by default

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/DscResource.Tests#3]
In the xDSCResourceDesigner module there is a function Test-xDscResource that tests if the resource fails many common tests including some warnings that the Get-TargetResource should return a hashtable and Test-TargetResource should return a boolen.

It would be quite nice if we tested this by default or at least pulled in a number of the functions into these tests to improve the quality of the code we are working on.

**Comment by vors** [comment]
:+1:

**Comment by joeyaiello** [comment]
Yeah, at the very least, we should run Test-xDscSchema if it's a MOF-based resource. Just ran into the problem of a schema definition on PowerShell/xHyper-V#13 that didn't validate due to an extra type.

**Comment by tysonjhayes** [comment]
This will be fixed when #6 gets merged.
