### ISSUE TITLE
A command with name 'Find-Package' is already available on this system

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#308]
#### Details of the problem, bug, or enhancement
Saw a new error today, when installing PowerShellGet.

https://github.com/PowerShell/DscResource.Tests/blob/a522ade40d959fc931dfc9eb2a4ec096b7e3afb1/AppVeyor.psm1#L42-L49

#### Verbose logs showing the problem (if applicable)
```
PackageManagement\Install-Package : A command with name 'Find-Package' is already available on this system. This module 'PackageManagement' may override the existing commands. If you still want to install this module 
'PackageManagement', use -AllowClobber parameter.
At C:\Program Files (x86)\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
```
https://ci.appveyor.com/project/PowerShell/sqlserverdsc/builds/21886114/job/072wm5llt4qyagc7?fullLog=true#L19

#### Suggested solution to the issue
Maybe we can check if the needed (latest) version is already installed?

**Comment by johlju** [comment]
This must have been a temporary glitch, can't reproduce.

**Comment by mmilirud-msft** [comment]
I'm hitting this on freshly deployed Azure VM with Windows Server 2016, trying to install https://www.powershellgallery.com/packages/Az.ApplicationMonitor/1.0.1 which requires Install-Module -Name PowerShellGet -Force to get newer PowerShellGet than ships with WS16.
