### ISSUE TITLE
Add test for having a new line at the end of a file

### ISSUE THREAD

**Issue by dcrreynolds** [PowerShell/DscResource.Tests#31]
This has come up a number of times in peer review and would be nice to automate.

**Comment by PlagueHO** [comment]
:+1: This would be pretty easy to add I think.

**Comment by dcrreynolds** [comment]
Ran the test against the default branch of all the DSC repos (count was 55). 17 had at least 1 file missing a new line.

xAzurePack, xAzureStorage, xCertificate, xDefender, xDnsServer, xExchange, xMySql, xNetworking, xPendingReboot, xPSDesiredStateConfiguration, xRemoteDesktopSessionHost, xRobocopy, xSharePoint, xSqlPs, xSQLServer, xStorage, xWindowsEventForwarding.

**Comment by KarolKaczmarek** [comment]
Thanks @dcrreynolds! Can you reopen pull requests with those tests, similar to #33 which unfortunately was merged and reverted ?
@mbreakey3 Can you add those new lines when you will be going through PSSA errors for these modules?

**Comment by dcrreynolds** [comment]
Done.
