### ISSUE TITLE
Pester seem to be installed, but still loads the wrong version

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#313]
#### Details of the problem, bug, or enhancement
I have seen a strange problem twice in the last few days. For some reason the wrong Pester version is used (my guess) even when we install the latest.
This is just happening in the Meta tests job, and the other jobs in the same build works correctly..

#### Verbose logs showing the problem (if applicable)
https://ci.appveyor.com/project/johlju/sqlserverdsc/builds/23015804/job/qkg7faynqh9g58qj?fullLog=true

#### Suggested solution to the issue
THis can be a temporary glitch in the AppVeyor build worker.
I think we should write out a verbose statement telling what Pester version do exist and what version is loaded. Or maybe we should force load the correct version after installing it? 🤔 

Let's wait a week or so to see if this issue disappears by itself.

**Comment by gaelcolas** [comment]
We should enforce a minimum version or people will have issues when they still have built-in version.
I address this in my draft PR

**Comment by johlju** [comment]
I have actually not seen this after I posted the issue, this was probably a glitch in AppVeyor. The latest version is always installed by the test framework, and should be used by the test framework since it imports the latest.

Closing this issue.
