### ISSUE TITLE
Links to DSC Test Templates Are Dead

### ISSUE THREAD

**Issue by mhendric** [PowerShell/DscResource.Tests#314]
Not sure if it's just me, but I have not been able to successfully search for the DSC test templates today, and the links referenced in the following URL are all 404 not found:

https://github.com/PowerShell/DscResource.Tests#templates-for-creating-tests

Dead links:

https://github.com/PowerShell/DscResources/blob/master/Tests.Template/integration_template.ps1
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1
https://github.com/PowerShell/DscResources/blob/master/Tests.Template/unit_template.ps1

**Comment by gaelcolas** [comment]
We moved the template to https://github.com/PowerShell/DscResource.Template

**Comment by mhendric** [comment]
The dead links in here probably need to be updated then.

https://github.com/PowerShell/DscResource.Tests#templates-for-creating-tests

**Comment by gaelcolas** [comment]
Will fix on Monday. Thanks for pointing out!
