### ISSUE TITLE
Generation of Wikipages throws an error

### ISSUE THREAD

**Issue by ykuijs** [PowerShell/DscResource.Tests#357]
#### Details of the problem, bug, or enhancement
When reviewing the AppVeyor log of a PR, I noticed that the WikiPages.ps1 is throwing errors with objects of type Microsoft.Management.Infrastructure.CimType. The code is adding '[]' to the type, but this results in the below error.

#### Verbose logs showing the problem (if applicable)
```
Cannot convert value "[]" to type "Microsoft.Management.Infrastructure.CimType". Error: "Unable to match the identifier name [] to a valid enumerator name. Specify one of the following enumerator names and try again:
Unknown, Boolean, UInt8, SInt8, UInt16, SInt16, UInt32, SInt32, UInt64, SInt64, Real32, Real64, Char16, DateTime, String, Reference, Instance, BooleanArray, UInt8Array, SInt8Array, UInt16Array, SInt16Array, UInt32Array, 
SInt32Array, UInt64Array, SInt64Array, Real32Array, Real64Array, Char16Array, DateTimeArray, StringArray, ReferenceArray, InstanceArray"
At C:\projects\sharepointdsc\DscResource.Tests\DscResource.DocumentationHelper\WikiPages.psm1:99 char:21
+                     $dataType += '[]'
+                     ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : SubstringDisambiguationEnumParseThrewAnException
```

#### Suggested solution to the issue
??

**Comment by PlagueHO** [comment]
Hi @ykuijs - I think I can see the problem:
The `DataType` property that is returned by `Get-MofSchemaObject` is type [Microsoft.Management.Infrastructure.CimType], but we're trying to append a string to it. There is no implict cast to string for this type.

E.g.
```powershell
$a = [Microsoft.Management.Infrastructure.CimType]::Real64
$a + '[]'
```

So the code needs to be changed to:
```powershell
$dataType = $dataType.ToString() + '[]'
```

I'll submit a PR to correct this.

**Comment by PlagueHO** [comment]
Should be fixed now @ykuijs - could you check?

**Comment by ykuijs** [comment]
With the move or SPDsc to the DSC Community org, our AppVeyor tests are broken. So right now I have  no possibility to test. We are working on fixing it asap.
