### ISSUE TITLE
ConvertTo-SpaceIndentation Breaks Files in Some Cases

### ISSUE THREAD

**Issue by mhendric** [PowerShell/DscResource.Tests#4]
Recently when I submitted a pull request for changes to the xExchange module, the automated tests failed on a couple files, and suggested running Get-TextFilesList | ConvertTo-SpaceIndentation to fix them. I decided to run this against the entire module, instead of just the files it suggested. After doing so and resubmitting the pull request, I got failures in multiple files that weren't otherwise modified other than running these commands against them. The failures are reported here:

https://ci.appveyor.com/project/PowerShell/xexchange/build/1.0.35

One of the files that broke is located here:

https://github.com/PowerShell/xExchange/blob/dev/DSCResources/MSFT_xExchMailboxDatabase/MSFT_xExchMailboxDatabase.psm1

**Comment by vors** [comment]
Sorry, didn't have a chance to look at it. I'm clearing the assignee, since I'm not actively working on DscResources at the moment.

**Comment by johlju** [comment]
@kwirkykat The helper function ConvertTo-SpaceIndentation doesn't seem to exists anymore. But it's referenced in the test here https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L94

Should we replace the text 'ConvertTo-SpaceIndentation' with something else, , or should be create a fixer function again, or should we remove the sentence entirely from the test? I suggest removing the text.

**Comment by kwirkykat** [comment]
@johlju I agree. Just remove the text
