### ISSUE TITLE
Make test for having a new line at the end of a file, actually cause a failure

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#40]
Right now it just warns, when it is run in AppVeyor (fails outside of AppVeyor)

**Comment by TravisEz13** [comment]
test was added due to #31

**Comment by KarolKaczmarek** [comment]
We should fix https://github.com/PowerShell/DscResources/issues/114 before addressing this one

**Comment by kwirkykat** [comment]
Closing this issue since this test exists and will now fail when newlines are not present at the end of files
