### ISSUE TITLE
psd1 encoding type

### ISSUE THREAD

**Issue by robplank** [PowerShell/DscResource.Tests#41]
In https://github.com/PowerShell/DscResource.Tests/blob/master/Meta.Tests.ps1 the "Files encoding" test test if all of the files are encoded in UTF-8.

Is this a best practice for module manifest files ? I'm wondering because New-Modulemanifest doesn't create the manifest in UTF-8.

**Comment by KarolKaczmarek** [comment]
Yes, we recommend UTF-8 (https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) , as git doesn't work well with UTF-16. 

Thanks for the feedback regarding New-ModuleManifest, I've escalated this to the appropriate team and hopefully it will get fixed soon. Until this happens, you will unfortunately need to convert the files into UTF-8 before checking in. Sorry for inconveniences this will cause.
