### ISSUE TITLE
Initialize-TestEnvironment should change PSModulePath at Process level for Unit Tests

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#58]
Currently the Initialize-TestEnvironment code changes the PSModuleRoot path to ensure that the correct module is tested. It is changed at the machine level to ensure that the correct path is set during Integration testing. However it should only be changed at the Process level for Unit tests.

These lines:
line https://github.com/PowerShell/DscResource.Tests/blob/master/TestHelper.psm1#L357
https://github.com/PowerShell/DscResource.Tests/blob/master/TestHelper.psm1#L419
should be wrapped in a check so that they only fire when $TestType = 'integration'

As noted by @narrieta in https://github.com/PowerShell/xActiveDirectory/pull/96#issuecomment-221394004

**Comment by KarolKaczmarek** [comment]
Fixed by https://github.com/PowerShell/DscResource.Tests/pull/67
