### ISSUE TITLE
Move Import-Module from Initialize-TestEnvironment to *.tests.ps1

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#59]
See [this discussion](https://github.com/PowerShell/xActiveDirectory/pull/96#issuecomment-221696166) for context.

The problem with Import-Module being inside the Intialize-TestEnvironment is that the DSC Resouce is loaded into the scope of the TestHelper.psm1 module. This means that tests for *-TargetResource have to be made inside an InModuleScope block.

@iainbrighton has tested the Import-Module cmdlet with -Scope Global set but it results in problems Mocking Get-TargetResource from the Test- and Set-TargetResource.

@Narrieta has suggested the solution to this would be to move the Import-Module cmdlet from out of the Initialization and into the Unit Test header for each resource. Import-Module is found [here](https://github.com/PowerShell/DscResource.Tests/blob/dev/TestHelper.psm1#L343).

This would be a breaking change for any resource unit **and** integration tests using the current test templates. Fixing these wouldn't be a major issue however but needs to be taken into account.

@KarolKaczmarek, @TravisEz13, @iainbrighton, @tysonjhayes?

**Comment by iainbrighton** [comment]
@PlagueHO @narrieta Let me clarify something: importing the module with `-Scope Global` doesn't break anything. I have issues mocking the internal calls when not using `InModuleScope`, but I think this is a Pester/testing issue and _nothing to do with the test template_.

**Comment by PlagueHO** [comment]
@iainbrighton - oh right - I misunderstood! So possibly -Scope Global will solve the problem. I'd prefer not to make a breaking change if possible - but a change definitely needs to be made. Perhaps just going with -Scope Global would be the better solution. Will wait for the others to weigh in. Thanks Iain!

**Comment by narrieta** [comment]
@iainbrighton @PlagueHO What are the issues mocking when using -Global? I did a quick test and didn't need InModuleScope, but I may be missing something:

```
PS> cat D:\nam\tmp\moduleToTest.psm1
function foo {
    _fooPrivate
}

function _fooPrivate {
    'foo'
}

Export-ModuleMember -Function foo

PS> cat D:\nam\tmp\helper.psm1
Import-Module -Force D:\nam\tmp\moduleToTest.psm1 -Global

function bar {
    "bar"
}

Export-ModuleMember -Function bar

PS> cat D:\nam\tmp\tests.ps1
Import-Module D:\nam\tmp\helper.psm1

Describe 'foo' {
    It 'Should return "foo"' {
        foo | Should Be 'foo'
    }

    Context 'When using a mock' {
        Mock _fooPrivate { 'bar' } -ModuleName moduleToTest

        It 'Should return "bar"' {
            foo | Should Be 'bar'
        }
    }
}

PS> D:\nam\tmp\tests.ps1
Describing foo
 [+] Should return "foo" 450ms
   Context When using a mock
    [+] Should return "bar" 636ms
PS>
```

Even if it works without issues, I am not fully convinced about importing at the global scope... may introduce other issues later. I still think the best choice is to import in the test script, but of course this needs to be weighted against the breaking changes/updates @PlagueHO  mentioned.

Thanks for all the work on this!

**Comment by PlagueHO** [comment]
@narrieta - I think I misunderstood @iainbrighton's original comment. I don't think the issues he had with Mocking were with the ```-Scope Global```. Iain's quote: " I have issues mocking the internal calls when not using InModuleScope, but I think this is a Pester/testing issue and nothing to do with the test template."

So I think we can use ```-Scope Global``` ok. I've tried this out on the xNetworking resource module and everything works correctly, but InModuleScope is used on all of those resources.

My feeling is that we implement the -Scope Global (along with the other changes I logged) and then revisit moving Import-Module out of the Initialize-TestEnvironment. I'm happy to submit a PR if I get everyone's agreement - @iainbrighton, @narrieta, @KarolKaczmarek, @TravisEz13, @mbreakey3 ?

Once this is in place we can start removing the InModuleScope from any existing tests on the modules. However, some tests will require additional work to get them to work without InModuleScope (because the some tests refer to LocalizationData variable declared by the module).

**Comment by narrieta** [comment]
@PlagueHO, @iainbrighton, @narrieta, @KarolKaczmarek, @TravisEz13, @mbreakey3: In my opinion, using -Global temporarily and changing the existing tests gradually is OK.

One possible way to reach into the localization data is to limit the use of InModuleScope to getting a reference to the data:

```
Describe '...' {
    $LocalizedData = InModuleScope -ModuleName moduleToTest -ScriptBlock {
        $LocalizedData
    }

    It '...' {
        $message = ...
        $LocalizedData.NeedsMoreInfo | Should Be $message
    }
}
```

**Comment by PlagueHO** [comment]
Awesome @narrieta - thank you for your extremely valuable input on this. I had actually added your LocalizedData suggestions to the [TestGuidlines.md](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md#using-variables-declared-by-the-module-in-tests) so hopefully people read it when creating tests. But if not, we can point them at that if they run into trouble when removing InModuleScope.

**Comment by iainbrighton** [comment]
@narrieta That works, but strangely doesn't work in the xADComputer tests I have!? I'll take another look as there might be something weird going on with the previous mock definitions/scopes.
