### ISSUE TITLE
Alias "ls" in MetaFixers.psm1 breaks Text files formatting test

### ISSUE THREAD

**Issue by gordonbondon** [PowerShell/DscResource.Tests#69]
[Here](https://github.com/PowerShell/DscResource.Tests/blob/dev/MetaFixers.psm1#L64) `ls` alias is used  instead of `Get-ChildItem` and this breaks [Text files formatting](https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L99) test on systems where this alias is removed (for example because git bash counterpart is used).

**Comment by kwirkykat** [comment]
Closed in #62
