### ISSUE TITLE
Restore-TestEnvironment remains PSModulePath added by Initialize-TestEnvironment

### ISSUE THREAD

**Issue by guitarrapc** [PowerShell/DscResource.Tests#70]
## Description of Issue

`Restore-TestEnvironment` could not handle `Initialize-TestEnvironment` added path.
## Detail

Initialize-TestEnvironment adding current Test DSC Module's Root Path, which retrieved at here https://github.com/PowerShell/DscResource.Tests/blob/dev/TestHelper.psm1#L347,  to the Machine's PSmodulePath at https://github.com/PowerShell/DscResource.Tests/blob/dev/TestHelper.psm1#L376

It's trying to pass $OldModulePath info, https://github.com/PowerShell/DscResource.Tests/blob/dev/TestHelper.psm1#L393 but ModuleRoot is remain after`Restore-TestEnvironment` has ran.
## Expectation

Should completely remove Test Module Path from PSModulePath.

**Comment by johlju** [comment]
Not sure this is still an issue, but let's keep this issue until we have written a unit/integration test for this.

**Comment by johlju** [comment]
We should add a new test case for this, and `Assert-MockCalled` here, so that `Set-PSModulePath` is called with the correct path.

https://github.com/PowerShell/DscResource.Tests/blob/4d8376d3201769156f2f72914d63656f4ff2a3d8/Tests/Unit/TestHelper.Tests.ps1#L993
