### ISSUE TITLE
Use Pester's TestDrive:/ in tests rather than a custom working directory

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/DscResource.Tests#73]
I've been looking through the Initialize-TestEnvironment method getting ready to retrofit this in to SharePointDsc and one of the questions I have about it for unit testing is why it sets up a custom path in the temp directory to save files in when [Pester does the exact same thing already](https://github.com/pester/Pester/wiki/TestDrive). In the cases of unit tests in SharePointDsc that we choose to not mock the file functions out, and in our integration tests, all of the path references point off to the TestDrive path. This gives us a fresh TestDrive that gets cleaned up between each Describe/Context block without it needing to be additional logic inside the DscResource.Tests scripts. 

I don't see any harm in having it in there, but it does seem a touch redundant given the tool we use for testing already covers this off. Just wanted to throw it out there for discussion to see if there is a use case for this that I'm not seeing or if it's something that could be removed in favour of what Pester gives us natively.

**Comment by PlagueHO** [comment]
I can answer this one @BrianFarnhill : when I wrote the original code I didn't knew about TesDrive: - and it hadn't occurred to me to update it. But I see no reason why we couldn't update it to use TestDrive: . Seems like a good idea to me. Good thinking!

**Comment by BrianFarnhill** [comment]
@PlagueHO Makes sense :) Not sure if/when I'll have time to make the change to this but we can leave this open and make sure that someone gets to it at some point.

**Comment by PlagueHO** [comment]
@BrianFarnhill - Sounds good to me! If you don't get to it first, I'll get to it eventually. I'll just pop it on the backlog (waaaay back there in the distance) :grin:

**Comment by kwirkykat** [comment]
@BrianFarnhill Yeah my answer is actually the same as @PlagueHO 's. :smile:  I only just learned about $TestDrive in a PR in xPSDSC this past weekend. I'd love to update the tests/testing framework to use it whenever I get the time......

**Comment by PlagueHO** [comment]
I think this one can probably be closed now because most of the resources have been moved over to use $TestDrive I think. Would that be correct @kwirkykat ?

**Comment by kwirkykat** [comment]
@PlagueHO Yes. Closing this as most if not all modules are now updated
