### ISSUE TITLE
The test results are not being populated in AppVeyor when using the common code to upload test results

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#89]
Using either the code in the `appveyor.yml` template most projects started with or the code in #85 the test results fail to upload.  
You can see this at https://ci.appveyor.com/project/PlagueHO/xNetworking/build/tests is empty.  It started with Pester 4.0.2 as mention in https://github.com/pester/Pester/issues/571#issuecomment-229414202.  

I know how to resolve this.  We should also ask if AppVeyor can fix this.

**Comment by TravisEz13** [comment]
Found this when making sure a bug has been filed on AppVeyor

**Comment by TravisEz13** [comment]
Also, There is [a work around](https://github.com/PowerShell/DscResource.Tests/pull/87/files#diff-bd6394d499b0c8d58bd248444d66be2dR75) in my PR to examine the $result object and use the AppVeyor PowerShell cmdlets to add the results.

**Comment by PlagueHO** [comment]
@TravisEz13 - is this one resolved now? Your work around is in and it seems to be working.

**Comment by TravisEz13** [comment]
fixed in #90
