### ISSUE TITLE
Common test to verify mofs compile should be run as an it-block

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#91]
*[Meta.Tests.ps1, line 430 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/85#-KcHA-LQnEcRNo-ZR-cJ:-KcH9chMuYD_yVHnZdAY:brin4og) ([raw file](https://github.com/powershell/dscresource.tests/blob/6e7251ce4edff8bd7dd734b67e5939482635b6e0/Meta.Tests.ps1#L430)):*
> ```PowerShell
>             Context -Name $exampleFile.Name {
> 
>                 try
> ```

If you see here I changed so this is run under an It-block. 
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/xSQLServerCommon.Tests.ps1#L37

Also added so it fails if the example does not contain an Example function.

---

**Comment by johlju** [comment]
I'm working on this one as well.

**Comment by johlju** [comment]
@PlagueHO I have this finished and have tested it on xSQLServer. But would like to test it on a few other modules before sending in the PR. Do you have a suggestion for modules worth testing on. Thinking you done a few rounds of testing already so you would now the best modules to test on. :smile:

**Comment by PlagueHO** [comment]
Hi @johlju - I've tested/done the following:
- xNetworking - complete and PR submitted (waiting review).
- xStorage (but also moved it over to the new xNetworking/SharePointDsc layout with Autodocumentation). However, the Pester 4.0.2 bug prevents the tests from failing so I can't submit till it's fixed.
- xCertificate - I will do this one, but I'm still in process of implementing the Cert Export resource so I'll complete the changes to this in parallel.
- xDFS - I've tested this one, but I'm moving to Autodocumentation in the xNetworking/SharePointDsc style.
- xComputerManagement - I've tested this one - but Pester 4.0.2 bug also causes problems.

I plan to do xADCSDeployment as well as some others as soon as I can. I think the tough ones will be xActiveDirectory and xWebAdministration. It is possible @tysonjhayes is working on xWebAdministration though - so might be worth checking with him on that one.

The Pester 4.0.2 bug(s) - https://github.com/pester/Pester/issues/697 - are causing many problems with existing repos. So even without the changes to DSCResource.tests, many repos are going to have problems. @kwirkykat and @mbreakey3 I think made changes to a couple of repos to force an older version of Pester to be used.

**Comment by PlagueHO** [comment]
@johlju - one further thing on this: it might be a good idea to raise an issue on each repo that we're currently moving over to this new model so we don't duplicate work.

**Comment by johlju** [comment]
@PlagueHO I will test my changes on xNetworking and SharePointDsc, which have examples and currently are working (not sure about SharePointDsc). For now I just want to test the examples test changes I did.

@PlagueHO I think if we start fixing to the new pattern in a repo it would be good idea to add an issue. If there is no issue then nobody is working on it. :)

**Comment by johlju** [comment]
@PlagueHO Well that did not work to test in those. Since the use the harness. :) I send in the PR anyway and we'll see what you think of it.

**Comment by tysonjhayes** [comment]
I am working on xWebAdministration, been sick the last few days so I'm a bit behind. 😁

**Comment by PlagueHO** [comment]
@tysonjhayes - Hope you're feeling better bud! :grin:

@johlju - my fork of xStorage uses Harness as well. My fork of [xComputerManagement](https://github.com/PlagueHO/xComputerManagement) doesn't though. You could try that one? It also has examples that have credentials etc so it would be a great test I reckon.

**Comment by johlju** [comment]
@PlagueHO I will test your branch of xStorage tomorrow!

**Comment by PlagueHO** [comment]
@Johlju - cool!  I've forced my xStorage branch to use the older Pester version (without all the bugs):
https://github.com/PlagueHO/xStorage/tree/Use-AppVeyor-Module

**Comment by johlju** [comment]
@PlagueHO Work like a charm:  https://ci.appveyor.com/project/johlju/xstorage/build/2.9.1.0#L726
