### ISSUE TITLE
Need to improve how we verify an example MOF should compile

### ISSUE THREAD

**Issue by TravisEz13** [PowerShell/DscResource.Tests#92]
*[Meta.Tests.ps1, line 439 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/85#-KcH7MwEsNUf2IUC0Is5:-KcH7MwFbjPsnRbhlbf2:box9oxb) ([raw file](https://github.com/powershell/dscresource.tests/blob/6e7251ce4edff8bd7dd734b67e5939482635b6e0/Meta.Tests.ps1#L439)):*
> ```PowerShell
>                     $params = @{}
>                     $command.Parameters.Keys | Where-Object { $_ -like "*Account" -or $_ -eq "Passphrase" } | ForEach-Object -Process {
>                         $params.Add($exampleFile, $mockCredential)
> ```

I can't see this $mockCredential being assigned anywhere? 

See
https://github.com/PowerShell/xSQLServer/blob/dev/Tests/xSQLServerCommon.Tests.ps1#L20

---

*[Meta.Tests.ps1, line 441 at r5](https://reviewable.io:443/reviews/powershell/dscresource.tests/85#-KcH7SXjtorcpdNAIl2h:-KcH7SXjtorcpdNAIl2i:bsigk6z) ([raw file](https://github.com/powershell/dscresource.tests/blob/6e7251ce4edff8bd7dd734b67e5939482635b6e0/Meta.Tests.ps1#L441)):*
> ```PowerShell
>                         $params.Add($exampleFile, $mockCredential)
>                     }
>                     $null = Example @params -OutputPath "TestDrive:\" -ErrorAction Continue -WarningAction SilentlyContinue
> ```

Don't we need it to load with a dummy configuration ? Like `-ConfigurationData $mockConfigurationData`? or is this done in another way?
See https://github.com/PowerShell/xSQLServer/blob/dev/Tests/xSQLServerCommon.Tests.ps1#L51

This can be added later: I also have seen a need for using an example provided ConfigurationData block. It should look for $ConfigurationData variable after dot-sourcing the example. If it exist it should use that to run the example. If not, it should use the default $mockConfigurationData.

---

**Comment by johlju** [comment]
I'm working on this one.
