### ISSUE TITLE
Detection of Repo root folder is not working correctly

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/DscResource.Tests#96]
Detection of Repo root folder is not working correctly for xNetworking/SharePointDsc repositories:
![2017-02-07_20-45-27](https://cloud.githubusercontent.com/assets/7589164/22682201/686ca354-ed76-11e6-958a-af5642b09514.png)

This bug is in this code here:
https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L18

This is only a problem for xNetworking/SharePointDsc

**Comment by johlju** [comment]
This line one should have -Hidden as well I think. 

https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L21
