### ISSUE TITLE
Problem with markdown lint errors MD013 and MD024

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#98]
In the xSQLServer repo the README.md currently have long lines and using the same header several times (like PSDscResource).

MD013
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.342.0#L864
MD024
https://ci.appveyor.com/project/johlju/xsqlserver/build/5.0.342.0#L1139

We have three options as I see it (not taking in account changing the README.md).

1. Add MD013 and MD024 to the .markdownlint.json file in this module.
2. Change the code so it uses the .markdownlint.json in the module being tested if it exist. I guess this line need to do change https://github.com/PowerShell/DscResource.Tests/blob/dev/gulpfile.js#L21 with some logic :)
3. I workaround it by parsing in the additional MD013 and MD024 in the .markdownlint.json after cloning DscResource.Tests in AppVeyor.yml.

I personally like option 2.

**Comment by TravisEz13** [comment]
I made this test a warning only with #102 due to multiple issues of this type until this can be resolved.  

I like option 2 as well.

**Comment by TravisEz13** [comment]
I'm also having issues getting MD002 and MD041 fixed.
https://github.com/PowerShell/xWindowsUpdate/pull/41#issuecomment-278217434
```
C:\projects\xwindowsupdate\README.md: 17: MD002 First header should be a top level header
C:\projects\xwindowsupdate\README.md: 1: MD041 First line in file should be a top level header
```
but line 1 is a top level header and 17 isn't the first header.

Option 2 would allow me to disable these rules, but feel free to take a look and see what I did wrong in the markdown.

**Comment by PlagueHO** [comment]
I'd go with Option 2 as well. Although like the PSSA rules it might be worth limiting the rules that can be suppressed.

Although because VSCode automatically underlines in red all MD violations regardless of any "suppression" we might add, it is sort of hard to identify violations of the other rules. So IMHO it is a better idea to solve all rule violations

Once you move over to (assuming you are planning to) automatic documentation generation (like SharePointDsc) then the MD violations stop existing because each of these "sections" gets moved into their own file. However the long lines should still be solved I reckon. My 2c!

**Comment by kwirkykat** [comment]
I would prefer that both MD013 and MD024 were disabled. They should be disabled in this central repo, but with the option 2 to overwrite them if necessary.

**Comment by PlagueHO** [comment]
@kwirkykat - as long as we can enable these rules on a repo basis, I'm ok with that - because we've put quite a bit of time making sure MD013 and MD024 are met on xNetworking, xStorage etc so we'd want to be able to keep enforcing this rule.

**Comment by johlju** [comment]
MD024 seems to be handle better by GitHub now. Saw that the other day. GitHub seems to have started to handle them by adding a number after each header that are similar. I haven't seen this before, but might have missed it.

Example in the README.md of the PSDscResources, for the Parameters header.

First: https://github.com/PowerShell/PSDscResources#parameters
Second: https://github.com/PowerShell/PSDscResources#parameters-1
Third:  https://github.com/PowerShell/PSDscResources#parameters-2

Just noting it here that overriding MD024 wouldn't be a problem.

When MD024 is disabled in the common tests, then I could just fix MD013 (in progress) in xSQLServer and opt-in for all the common tests, then this issue would be a non-issue for xSQLServer at least. 

But we need to add the functionality to enable MD024 for those repos that still like to enforce it. 

I can put some time on this and send in a proposed PR for this issue.

**Comment by johlju** [comment]
I sent in a PR for this in PR #146.
