### ISSUE TITLE
Wrong output at the end of the script

### ISSUE THREAD

**Issue by johlju** [PowerShell/DscResource.Tests#99]
Getting wrong output at the end of the tests I think; System.Management.Automation.PSCustomObject

``` 
[Build Info] [02/07/2017 18:42:14] Test result Type: System.Management.Automation.PSCustomObject
```

https://ci.appveyor.com/project/PowerShell/xsqlserver/build/5.0.838.0#L5389

**Comment by TravisEz13** [comment]
I think I blindly copied this from my prototype code to help debug certain issues... it should be changed to a write verbose...
